# Generated by Django 5.1.5 on 2025-05-17 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payslip',
            old_name='id_number',
            new_name='employee',
        ),
    ]
